USE [master]
GO

/****** Object:  Database [CustomerFeedbackDB]    Script Date: 11/11/2025 4:48:02 PM ******/
CREATE DATABASE [CustomerFeedbackDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CustomerFeedbackDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\CustomerFeedbackDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CustomerFeedbackDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\CustomerFeedbackDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CustomerFeedbackDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CustomerFeedbackDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CustomerFeedbackDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CustomerFeedbackDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CustomerFeedbackDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CustomerFeedbackDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [CustomerFeedbackDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CustomerFeedbackDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CustomerFeedbackDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CustomerFeedbackDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CustomerFeedbackDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CustomerFeedbackDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CustomerFeedbackDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CustomerFeedbackDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CustomerFeedbackDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CustomerFeedbackDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CustomerFeedbackDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CustomerFeedbackDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CustomerFeedbackDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CustomerFeedbackDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CustomerFeedbackDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CustomerFeedbackDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CustomerFeedbackDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CustomerFeedbackDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [CustomerFeedbackDB] SET  MULTI_USER 
GO

ALTER DATABASE [CustomerFeedbackDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CustomerFeedbackDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CustomerFeedbackDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CustomerFeedbackDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [CustomerFeedbackDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CustomerFeedbackDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [CustomerFeedbackDB] SET QUERY_STORE = ON
GO

ALTER DATABASE [CustomerFeedbackDB] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [CustomerFeedbackDB] SET  READ_WRITE 
GO


